# Generated by Django 5.2 on 2025-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category_price_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='valid_from',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='valid_to',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='full_title',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
