# 1. Build Angular
FROM node:20-alpine AS builder

WORKDIR /app

#COPY package*.json ./
#RUN npm ci

#COPY . .

#RUN npm run build -- --configuration=production

#FROM nginx:stable-alpine
#COPY --from=builder /app/dist/frontend/browser /usr/share/nginx/html/


