version: '3.9'

services:
  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: nginx -g "daemon off;"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro

  db:
    image: postgres:14
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - frontend_build:/usr/share/nginx/html:ro

volumes:
  pg_data:
  static_volume:
  frontend_build:
