
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  backend:
    build: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
       DJANGO_SETTINGS_MODULE: core.settings.base
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate && 
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    build: ./frontend
    command: nginx -g "daemon off;"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro


  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - frontend_build:/usr/share/nginx/html:ro

volumes:
  pg_data:
  static_volume:
  frontend_build:
